export const FETCH_AIR_QUALITY_DATA_REQUEST = 'FETCH_AIR_QUALITY_DATA_REQUEST';
export const FETCH_AIR_QUALITY_DATA_SUCCESS = 'FETCH_AIR_QUALITY_DATA_SUCCESS';
export const FETCH_AIR_QUALITY_DATA_FAIL = 'FETCH_AIR_QUALITY_DATA_FAIL';